repos:
  - repo: local
    hooks:
      - id: backend-ruff
        name: Run ruff
        entry: ruff check .
        language: system
        pass_filenames: false
      - id: backend-black-check
        name: Check code formatting with black
        entry: black --check .
        language: system
        pass_filenames: false
      - id: Run tests
        name: Run tests
        entry: docker exec litestar-app pytest
        language: system
        pass_filenames: false
