services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: litestar-app
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_LOG_LEVEL=info
    command: /app/.venv/bin/uvicorn app:app --reload

  postgres:
    image: postgres:16
    container_name: litestar-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data