services:
  app:
    build: .
    container_name: litestar-app
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_LOG_LEVEL=info
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app:app --reload
    develop:
      watch:
        - action: sync
          path: src
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./pyproject.toml


  postgres:
    image: postgres:16
    container_name: litestar-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      retries: 5
      start_interval: 1s
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data