services:
  app:
    build: .
    container_name: litestar-app
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_LOG_LEVEL=info
      - PYTHONPATH=/app/src
      - DEBUG=False
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "alembic upgrade head && uvicorn app:app --reload"
    volumes:
      - ./src:/app/src
      - session_data:/app/session_data


  postgres:
    image: postgres:16
    container_name: litestar-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 2s
      retries: 5
      start_interval: 2s
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data


volumes:
  session_data:
